# Generated by Django 5.0.7 on 2024-07-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
