# Generated by Django 5.0.7 on 2024-07-26 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamflow', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='teamflow.project'),
            preserve_default=False,
        ),
    ]
