# Generated by Django 5.0.7 on 2024-08-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamflow', '0003_comment_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(),
        ),
    ]
