# Generated by Django 5.0.7 on 2024-08-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamflow', '0005_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
